config/routes.rb
Tammany::Application.routes.draw do
  
  get "page/dashboard"
  resources :issues, except: [:destroy]

  get "page/confirm"

  devise_for :caseworkers
  resources :caseworkers, only: [:show, :index]

  root :to => 'page#home'

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  attr_accessible :name
  
  has_many :issues
end

app/models/caseworker.rb
class Caseworker < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  attr_accessible :name, :title
  
  has_many :issues
end

app/models/constituent.rb
class Constituent < ActiveRecord::Base
  attr_accessible :address, :cell, :email, :fname, :landline, :lname
  
  has_many :issues
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :priority_level
  belongs_to :agency
  belongs_to :status
  belongs_to :caseworker
  belongs_to :constituent
  
  has_many :issue_updates

  attr_accessible :date, :description, :location, :priority_level, :agency, :status, :caseworker, :constituent,
    :priority_level_id, :agency_id, :status_id, :caseworker_id, :constituent_id, :issue_updates_attributes, :issue_update

  after_create :send_confirm_email
  after_create :send_confirm_sms
  
  accepts_nested_attributes_for :issue_updates
  
  def name
    "#{constituent.lname}-#{id}"
  end
 
  private
  
  def send_confirm_email
    IssueMailer.issue_create(self.constituent.email, self.id, self.description).deliver
  end
  
  def send_confirm_sms
    unless Rails.env == "development"
    from_number = "+17188784925"
    to_number = "+13143244262"
    issue_id = self.id
    @client = Twilio::REST::Client.new ENV['TWILIO_SID'], ENV['TWILIO_TOKEN']
    @client.account.sms.messages.create(
      :body => "Your representative has received your issue. It is ID# #{issue_id}.",
      :to => to_number,
      :from => from_number)
    end
  end

end

app/models/issue_update.rb
class IssueUpdate < ActiveRecord::Base
  belongs_to :issue
  attr_accessible :note, :issue, :issue_id
end

app/models/issue_updates.rb
class IssueUpdates < ActiveRecord::Base
  belongs_to :issue
  attr_accessible :note, :issue
end

app/models/priority_level.rb
class PriorityLevel < ActiveRecord::Base
  attr_accessible :name
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :authenticate_caseworker!
  
  def after_sign_in_path_for(caseworker)
    page_dashboard_path
  end
  
end

class SessionsController < ApplicationController
  skip_before_filter :authenticate_caseworker!
end

class PageController < ApplicationController
  skip_before_filter :authenticate_caseworker!, :only => [:home]
end

app/controllers/caseworkers_controller.rb
class CaseworkersController < ApplicationController
  def index
    @caseworkers = Caseworker.all
  end

  def show
    @caseworker = Caseworker.find(params[:id])
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @issues = Issue.all
  end

  def show
    @issue = Issue.includes(:issue_updates).find(params[:id])
  end

  def new
    @issue = Issue.new
    @constituent = Constituent.new
  end

  def create
    @constituent = Constituent.create(params[:issue][:constituent])
    
    @issue = Issue.new(params[:issue].reject{ |k,v| k == 'constituent' })
    @issue.constituent = @constituent
    @issue.caseworker = current_caseworker
    

    if @issue.save
      flash[:notice] = "New Issue Created"
      redirect_to page_dashboard_path
    else
      flash[:error] = "There was a problem, try again"
      redirect_to :new
    end
    
  end

  def edit
    @issue = Issue.find(params[:id])
    @issue_update = IssueUpdate.new
  end

  def update
    @issue = Issue.find(params[:id])
    @issue.update_attributes(params[:issue].reject{ |k,v| k == 'issue_update' })
    @issue_update = IssueUpdate.create(issue_id: @issue.id, note: params[:issue][:issue_update][:note])
    
    redirect_to page_dashboard_path
  end
  
  private
  
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  	redirect_to page_dashboard_path if current_caseworker
  end
  
  def confirm
  end

  def dashboard
  	@issues = Issue.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caseworkers_helper.rb
module CaseworkersHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/caseworkers/create.html.erb
<h1>Caseworkers#create</h1>
<p>Find me in app/views/caseworkers/create.html.erb</p>

app/views/caseworkers/edit.html.erb
<h1>Caseworkers#edit</h1>
<p>Find me in app/views/caseworkers/edit.html.erb</p>

app/views/caseworkers/index.html.erb
<h1>Caseworkers#index</h1>
<p>Find me in app/views/caseworkers/index.html.erb</p>

app/views/caseworkers/new.html.erb
<h1>Caseworkers#new</h1>
<p>Find me in app/views/caseworkers/new.html.erb</p>

app/views/caseworkers/show.html.erb
<h1>Caseworkers#show</h1>
<p>Find me in app/views/caseworkers/show.html.erb</p>

app/views/caseworkers/update.html.erb
<h1>Caseworkers#update</h1>
<p>Find me in app/views/caseworkers/update.html.erb</p>

app/views/constituents/_constituent.html.erb
<div class="constituent">
  <h4> Constituent Info</h4>
    <p>Name: <%= "#{constituent.fname} #{constituent.lname}" %> </p>
		
		<p>Address: <%= constituent.address %></p>
    <p>Phone: <%= constituent.cell || constituent.landline %></p>
    <p>Email: <%= constituent.email %></p>
    
	</div>
</div>

app/views/issue_updates/_issue_update.html.erb
<div class="update">
		<p><%= issue_update.note %>  </p>
		
		<p>Date Created:<%= issue_update.created_at.to_date %></p>
</div>

app/views/issue_updates/_issue_updates.html.erb
<div class="update">
		<p><%= issue_update.note %>  </p>
		
		<p>Date Created:<%= issue_update.created_at.to_date %></p>
</div>

app/views/issues/_details.html.erb
<div class="row">
  <div class="issue">
  		<h3><%= @issue.name %> <small><%= @issue.priority_level.name %></small></h3>
		
  		<p>Date Created:<%= @issue.created_at.to_date %> Status: <%= @issue.status.name %></p>
    
      <p>Description: <%= @issue.description %></p>
      
      <p>Caseworker: <%= @issue.caseworker.name %></p>
  </div>

  <%= render @issue.constituent %>
  

  <h4> Updates</h4>
  <%= render @issue.issue_updates %>

  <%= link_to("Update", edit_issue_path(@issue), :class => 'button') %>
</div>

app/views/issues/_issue.html.erb
	<div class="issue">
			<h3><%= link_to issue.name, issue_path(issue)  %> <small>Priority: <%= issue.priority_level.name %></small></h3>
			
			<p>Date Created: <%= issue.created_at.to_date %> <br />
      Status: <%= issue.status.name %> <br />
      <%= link_to 'View Issue Details', issue_path(issue)  %> | <%= link_to("Create an Update", edit_issue_path(issue)) %>
      </p>
	</div>

app/views/issues/edit.html.erb
<div class="row">
<h1>Edit and Issue</h1>

<%= simple_form_for @issue do |f| %>

<div class="row">
  <div class="large-2  large-offset-1 columns">
    <%= f.label :caseworker, "Case Worker" %>
  </div>
  <div class="large-6 columns end">
    <%= f.association :caseworker, :label => false %>
  </div>
</div>

<div class="row">
  <div class="large-2  large-offset-1 columns">
    <%= f.label :status, "Status" %>
  </div>
  <div class="large-6 columns end">
    <%= f.association :status, :label => false %>
  </div>
</div>
    
<%= f.fields_for @issue_update do |update| %>

<div class="row">
  <div class="large-2  large-offset-1 columns">
    <%= update.label :note, "Note" %>
  </div>
  <div class="large-6 columns end">
    <%= update.input :note, :label => false %>
  </div>
</div>

<% end %>
<br />

<div class="row">
  <div class="large-8  large-offset-1 columns end">
    <%= f.button :submit %>
  </div>
<% end%>
</div>

app/views/issues/index.html.erb
<h1>Issues</h1>

<div class="row">
<div class="large-4">
 	<%= render @issues %>

</div>
</div>

app/views/issues/new.html.erb
<div class="row">
  <h1>Create a New Issue</h1>
  <%= simple_form_for @issue do |f| %>
  <h3>Constituent Information</h3>
    <%= f.fields_for @constituent do |c| %>
    
    <div class="row">
      <div class="large-2  large-offset-1 columns">
        <%= c.label :fname, "First Name" %>
      </div>
      <div class="large-6 columns end">
        <%= c.input :fname, :label => false %>
      </div>
    </div>
    
    <div class="row">
      <div class="large-2  large-offset-1 columns">
        <%= c.label :lname, "Last Name" %>
      </div>
      <div class="large-6 columns end">
        <%= c.input :lname, :label => false %>
      </div>
    </div>
    
    <div class="row">
      <div class="large-2  large-offset-1 columns">
        <%= c.label :address, "Address" %>
      </div>
      <div class="large-6 columns end">
        <%= c.input :address, :label => false %>
      </div>
    </div>
    
    <div class="row">
      <div class="large-2  large-offset-1 columns">
        <%= c.label :cell, "Cell Phone" %>
      </div>
      <div class="large-6 columns end">
        <%= c.input :cell, :label => false %>
      </div>
    </div>
    
    <div class="row">
      <div class="large-2  large-offset-1 columns">
        <%= c.label :landline, "Home Phone" %>
      </div>
      <div class="large-6 columns end">
        <%= c.input :landline, :label => false %>
      </div>
    </div>
    
    <div class="row">
      <div class="large-2  large-offset-1 columns">
        <%= c.label :email, "Email" %>
      </div>
      <div class="large-6 columns end">
        <%= c.input :email, :label => false %>
      </div>
    </div>
    <% end %>
  
  <h3>Issue Information</h3>
  <div class="row">
    <div class="large-2  large-offset-1 columns">
      <%= f.label :date, "Date" %>
    </div>
    <div class="large-6 columns end">
      <%= f.input :date, :label => false %>
    </div>
  </div>
  
  <div class="row">
    <div class="large-2  large-offset-1 columns">
      <%= f.label :description, "Description" %>
    </div>
    <div class="large-6 columns end">
      <%= f.input :description, :label => false %>
    </div>
  </div>
  
  <div class="row">
    <div class="large-2  large-offset-1 columns">
      <%= f.label :location, "Location" %>
    </div>
    <div class="large-6 columns end">
      <%= f.input :location, :label => false %>
    </div>
  </div>
  
  <div class="row">
    <div class="large-2  large-offset-1 columns">
      <%= f.label :agency, "Agency" %>
    </div>
    <div class="large-6 columns end">
      <%= f.association :agency, :label => false %>
    </div>
  </div>
  
  <div class="row">
    <div class="large-2  large-offset-1 columns">
      <%= f.label :priority_level, "Priority Level" %>
    </div>
    <div class="large-6 columns end">
      <%= f.association :priority_level, :label => false %>
    </div>
  </div>
  
  <div class="row">
    <div class="large-2  large-offset-1 columns">
      <%= f.label :status, "Status" %>
    </div>
    <div class="large-6 columns end">
      <%= f.association :status, :label => false %>
    </div>
  </div>
    
  
    
    <%= f.button :submit %>
  <% end%>

</div>

app/views/issues/show.html.erb
  <%= render 'details' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Tammany</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <script type="text/javascript" src="//use.typekit.net/rej1wrw.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <!-- header -->
    <div class="header clearfix">
      <div class="left logo"><h2><%= link_to "TAMMANY", root_path %></h2></div>
      
      <div class="right">
        <% if caseworker_signed_in? %>
          <div class="menu"><%= link_to "About", root_path %>    |    <%= link_to('Logout',  destroy_caseworker_session_path, :method => :delete)  %></div>        
       
        <% else %>
          <div class="menu"><%= link_to "About", root_path %>    |    <%= link_to('Login', new_caseworker_session_path)  %></div>
        <% end %>
        </div>
      </div>
    </div>

   
   
    <div class="row">
      <%= yield %>
    </div>
  

    <%= javascript_include_tag "application" %>
  </body>
</html>
  </div>

app/views/page/confirm.html.erb
<h1>Congrats!</h1>
<p>You're logged in.</p>

app/views/page/dashboard.html.erb
<div class="row">
  <h1>Current Issues</h1>
  <p><%= link_to 'Create New Issue', new_issue_path, :class => 'button small' %>
	<div class="large-4">
	  <%= render @issues %>
	</div>
	
</div> 

app/views/page/home.html.erb
<div class="large-12">
	<div class="home"></div>
	<div class="row dark-background">
		<div class="large-12">
		<ul class="small-block-grid-3 intro">
		  <li class="text">
		  	<div class="blurb">
		  	<h1 class="center number">1</h1>
		  	<h4 class="title">Record Issue</h4>
		  	<p>Login to you account. Create a new case form using an editable form.</p>
		  	<div>
		  </li>

		  <li class="text">
		  	<h1 class="center number">2</h1>
		  	<h4 class="title">Manage Progress</h4>
		 		<p>Track and manage issues using a newsfeed and intuitive dashboard with smart analytics on issues.</p>
		  </li>
		  <li class="text">
		  	<h1 class="center number">3</h1>
		  	<h4 class="title">Update Constituent</h4>
		  	<p>Contact your constituents via email, text, or phone to update them on their issue.</p>
		  </li>
		</ul>
	</div>
	</div>
</div>

<div class="large-10 large-offset-1 pitch">
<h3>A new approach to handling issues with your constituents.</h3>
</div>